import type { Metadata } from "next";
import { TextProvider } from "@/context/textContext";
import { wordFromJson } from "@/types/synonym";
import { AppThemeProvider } from "@/theme/themeProvider";


export const metadata: Metadata = {
  title: "Docu-Mixer!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppThemeProvider>
    <html lang="en">
      <body>
        <TextProvider>
          {children}
        </TextProvider>
      </body>
    </html>
    </AppThemeProvider>
  );
}
